### ISSUE TITLE
Methodology in Application Process

### ISSUE THREAD

**Issue by ChrisCates** [evykassirer/playing-the-internship-game#2]
Something that far too few people do on their job search is writing projects specifically targeted towards their prospective company and then using it as an interactive cover letter.

I find that the students I have placed have high success rates with this principle methodology.

Here's mock case scenario:
1. A person wants to be part of Google.
2. Person deeply vested and interested in AI.
3. Person does research on Tensorflow.
4. Person forks Tensorflow project. Writes a wrapper for a specific neural network technique (Alexnet for example).
5. Person writes a blog post, website demonstrating processes, methodology and use case for the technique.
6. Person prospects recruiters at Google and then showcases project and case study as an informal cover letter.

May pose as an interesting process for you.

**Comment by evykassirer** [comment]
added in c4896ee677add2
