### ISSUE TITLE
Open Source Contributions

### ISSUE THREAD

**Issue by ChrisCates** [evykassirer/playing-the-internship-game#3]
Another great methodology and approach to building a strong resume and work experience is to target and prospect large Open Source Projects.

Considering this, you must do significant research on your prospective project.
I will demonstrate a process to build an exceptional leverage from said Open Source Project(s).

In a mock scenario, let's consider I want a job at Facebook as a systems level engineer.

1. Do research on Facebook's Open Source Ecosystem (discover Proxygen and other libraries).
2. Understand the process and methodologies to applying patches and features to the project.
3. Iterate a patch or feature on the project several times.
4. Connect and collaborate with the package maintainers.
5. Use package maintainers as a reference and/or letter of recommendation for Facebook.

**Comment by evykassirer** [comment]
added stuff about open source in dd36e3e59d0b - thanks!
