### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rusrushal13** [evykassirer/playing-the-internship-game#4]
I am right now attending an internship in Germany and one thing that I am missing that we need to document our work. Can you please explain more on this aspect?
(My NDA restrict me to put the work on the Github)

**Comment by evykassirer** [comment]
to clarify: by documentation do you mean things like commenting your code and writing guides for others to explain how your code works?

**Comment by rusrushal13** [comment]
No I meant as every company have non disclosure agreements and due to that we can't talk or upload any codes on Github which are related to work so how to document your internship?

**Comment by evykassirer** [comment]
Ah, good thing I asked!

So you want to know how to talk about it on your resume even though it's non disclosure?

**Comment by rusrushal13** [comment]
Yes 😀

**Comment by evykassirer** [comment]
A few suggestions on this:

- ask your manager/employer - they know what things you can talk about and what things you can't. Hopefully your manager's job is to help your career, so they would be happy to help with your resume and suggest ways to phrase what you did without giving anything secret away
- Talk generally about stuff and say whatever you can. Can you say what technology you used? Can you talk about very broadly what team you're on? What your responsibilities were? Did you work with a big team or work individually? Try to find any details about what you're doing that you can share

Does that help? Feel free to followup with any more questions

**Comment by rusrushal13** [comment]
How did you manage it?

**Comment by evykassirer** [comment]
Exactly as I described above

**Comment by rusrushal13** [comment]
Thanks Evy 😉
