### ISSUE TITLE
fix markdown list nesting

### ISSUE THREAD

**Issue by evykassirer** [evykassirer/playing-the-internship-game#5]
there's an issue that needs to be looked into where nested lists aren't being rendered right - it just shows one level of bullets

friend sent me this doc to show me:
https://docs.google.com/document/d/1EK4qUDqbnoIcwG68e_AdINqpTNeflpbmJNNllvKKk10/edit

**Comment by evykassirer** [comment]
fixed

thanks @9at8 !

(I actually had to go in and make it 4 space indentation, which I didn't realize until I redeployed. Related to https://github.com/waylan/Python-Markdown/issues/3)

**Comment by 9at8** [comment]
You're welcome! 
I faced this issue earlier while I was taking down some notes. Thought I could help :)
